/**
 * Generate TypeScript type declarations + the MCP discovery index from the
 * local apiV2.yaml.
 *
 *   bun run scripts/generate-types.ts
 *
 * Emits:
 *   packages/sdk/src/generated/types.d.ts      — full type declarations (openapi-typescript)
 *   packages/sdk/src/generated/mcp-index.json  — per-endpoint operation metadata, field
 *                                                names, and named-schema refs for the
 *                                                MCP `beds24_discover` tool.
 *
 * Both are auto-generated — do not edit either by hand. The discovery-index
 * logic lives here (self-contained) rather than imported from schema.ts: the
 * restructured schema.ts dropped the getEndpointMeta/getFieldNames/getSchemaRef
 * helpers, so we derive the index from the spec object we already parsed for
 * openapi-typescript instead of re-reading the file.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import openapiTS, { astToString, type OpenAPI3 } from "openapi-typescript";
import yaml from "js-yaml";

const SPEC_PATH = join(process.cwd(), "packages", "sdk", "apiV2.yaml");
const OUT_DIR = join(process.cwd(), "packages", "sdk", "src", "generated");
const DTS_PATH = join(OUT_DIR, "types.d.ts");
const MCP_PATH = join(OUT_DIR, "mcp-index.json");

const BANNER = `// AUTO-GENERATED by scripts/generate-types.ts — do not edit.\n// Source: packages/sdk/apiV2.yaml (mirror of https://beds24.com/api/v2/apiV2.yaml)\n// Regenerate with: bun run generate-types.ts\n`;

/** A loose JSON-schema-like node in the OpenAPI document. */
type JsonNode = { [key: string]: unknown };

const METHOD_ORDER = ["get", "post", "put", "delete", "patch"] as const;

/** A single operation parameter, flattened for tool consumption. */
interface Parameter {
	name: string;
	location: string;
	required: boolean;
	schemaType: string;
	description: string;
}

/** Operation-level metadata (summary/description/tags/parameters/operationId). */
interface EndpointMeta {
	method: string;
	path: string;
	operationId: string;
	summary: string;
	description: string;
	tags: string[];
	parameters: Parameter[];
}

/** A resolved endpoint schema, request and/or response. */
interface EndpointSchema {
	request?: JsonNode;
	response?: JsonNode;
}

async function main(): Promise<void> {
	// openapi-typescript's redoc-based parser rejects a bare file-path string
	// ("Unsupported schema format, expected `openapi: 3.x`"), so we parse the
	// YAML ourselves and hand it the resolved JSON object.
	let doc: JsonNode;
	try {
		doc = yaml.load(readFileSync(SPEC_PATH, "utf8")) as JsonNode;
	} catch (e) {
		console.error(`[beds24] failed to parse ${SPEC_PATH}: ${(e as Error).message}`);
		process.exit(1);
	}

	let ast;
	try {
		ast = await openapiTS(doc as unknown as OpenAPI3);
	} catch (e) {
		console.error(`[beds24] openapi-typescript failed to generate types: ${(e as Error).message}`);
		process.exit(1);
	}

	const dts = `${BANNER}\n${astToString(ast)}`;

	mkdirSync(OUT_DIR, { recursive: true });
	writeFileSync(DTS_PATH, dts, "utf8");
	console.error(`[beds24] wrote ${DTS_PATH} (${dts.length} bytes).`);

	buildMcpIndex(doc);
}

/** Resolve a `$ref` pointer like `#/components/schemas/things` to its node. */
function resolveRef(doc: JsonNode, ref: string): JsonNode | undefined {
	const parts = ref.replace(/^#\//, "").split("/");
	let cur: unknown = doc;
	for (const part of parts) {
		if (cur && typeof cur === "object") {
			cur = (cur as Record<string, unknown>)[part];
		} else {
			return undefined;
		}
	}
	return cur as JsonNode | undefined;
}

/**
 * Recursively inline `$ref`, and merge `allOf` / collect `oneOf` alternatives
 * into a single normalized object schema suitable for field extraction.
 */
function normalize(doc: JsonNode, node: JsonNode | undefined): JsonNode | undefined {
	if (!node || typeof node !== "object") return node;

	if (typeof node.$ref === "string") {
		return normalize(doc, resolveRef(doc, node.$ref));
	}

	const out: JsonNode = {};

	if (Array.isArray(node.allOf)) {
		const merged: JsonNode = { type: "object", properties: {}, required: [] };
		for (const member of node.allOf) {
			const norm = normalize(doc, member as JsonNode);
			if (!norm || typeof norm !== "object") continue;
			if (norm.properties && typeof norm.properties === "object") {
				merged.properties = {
					...(merged.properties as JsonNode),
					...(norm.properties as JsonNode),
				};
			}
			if (Array.isArray(norm.required)) {
				(merged.required as unknown[]).push(...(norm.required as unknown[]));
			}
		}
		if (node.description) merged.description = node.description;
		return merged;
	}

	if (Array.isArray(node.oneOf)) {
		return {
			...node,
			oneOf: (node.oneOf as JsonNode[]).map((n) => normalize(doc, n)),
		};
	}

	for (const [key, value] of Object.entries(node)) {
		if (key === "properties" && value && typeof value === "object") {
			const props: JsonNode = {};
			for (const [pname, pschema] of Object.entries(value as JsonNode)) {
				props[pname] = normalize(doc, pschema as JsonNode) ?? pschema;
			}
			out.properties = props;
		} else if (key === "items" && value && typeof value === "object") {
			out.items = normalize(doc, value as JsonNode);
		} else {
			out[key] = value;
		}
	}
	return out;
}

/** Pull request + response body schemas out of an operation object (raw, un-normalized). */
function extractEndpointSchemas(op: JsonNode): EndpointSchema {
	const out: EndpointSchema = {};

	const rb = op.requestBody as JsonNode | undefined;
	if (rb) {
		const media = (rb.content as JsonNode | undefined)?.["application/json"] as
			| JsonNode
			| undefined;
		if (media?.schema) {
			// POST bodies are arrays of items; one item is the schema of interest.
			const schema = media.schema as JsonNode;
			out.request =
				schema.type === "array"
					? (schema.items as JsonNode | undefined) ?? schema
					: schema;
		}
	}

	const responses = (op.responses ?? {}) as Record<string, JsonNode>;
	for (const code of ["200", "201"]) {
		const resp = responses[code];
		if (!resp || typeof resp !== "object") continue;
		const media = ((resp as JsonNode).content as JsonNode | undefined)?.[
			"application/json"
		] as JsonNode | undefined;
		if (media?.schema) {
			out.response = media.schema as JsonNode;
			break;
		}
	}

	return out;
}

/** Build the per-endpoint request/response schema map for the whole spec. */
function buildEndpointMap(doc: JsonNode): Map<string, EndpointSchema> {
	const endpoints = new Map<string, EndpointSchema>();
	const paths = (doc.paths ?? {}) as Record<string, JsonNode>;
	for (const path of Object.keys(paths)) {
		const node = paths[path]!;
		for (const method of METHOD_ORDER) {
			const op = node[method];
			if (!op || typeof op !== "object") continue;
			endpoints.set(`${method.toUpperCase()} ${path}`, extractEndpointSchemas(op as JsonNode));
		}
	}
	return endpoints;
}

/** All `METHOD /path` keys present in the spec, sorted. */
function listEndpoints(doc: JsonNode): string[] {
	const paths = (doc.paths ?? {}) as Record<string, JsonNode>;
	const keys: string[] = [];
	for (const path of Object.keys(paths)) {
		const node = paths[path]!;
		for (const method of METHOD_ORDER) {
			if (node[method]) keys.push(`${method.toUpperCase()} ${path}`);
		}
	}
	return keys.sort();
}

/** The schema-reference name the request/response body points to via a top-level `$ref`. */
function getSchemaRef(
	endpoints: Map<string, EndpointSchema>,
	endpoint: string,
	direction: "request" | "response",
): string | null {
	const ep = endpoints.get(endpoint);
	if (!ep) return null;
	const raw = (direction === "request" ? ep.request : ep.response) as JsonNode | undefined;
	if (!raw || typeof raw !== "object") return null;
	const ref = (raw as JsonNode).$ref;
	if (typeof ref !== "string") return null;
	return ref.split("/").pop() ?? null;
}

/** Top-level property names of the normalized request/response schema for an endpoint. */
function getFieldNames(
	doc: JsonNode,
	endpoints: Map<string, EndpointSchema>,
	endpoint: string,
	direction: "request" | "response",
): string[] {
	const ep = endpoints.get(endpoint);
	if (!ep) return [];
	const raw = (direction === "request" ? ep.request : ep.response) as JsonNode | undefined;
	const node = normalize(doc, raw);
	if (!node || typeof node !== "object") return [];
	const properties = (node.properties as JsonNode | undefined) ?? {};
	return Object.keys(properties).sort();
}

/** Key a parameter by name+location so operation params override path params. */
function paramKey(p: JsonNode): string {
	return `${String(p.name ?? "")}/${String(p.in ?? "")}`;
}

/** Resolve a parameter entry if it's a `$ref`, returning a concrete object. */
function resolveParameter(doc: JsonNode, p: JsonNode): JsonNode | undefined {
	if (!p || typeof p !== "object") return undefined;
	if (typeof p.$ref === "string") {
		return resolveRef(doc, p.$ref);
	}
	return p;
}

/** Flatten one OpenAPI parameter object into a Parameter. */
function flattenParameter(p: JsonNode): Parameter {
	const schema = (p.schema as JsonNode) ?? {};
	return {
		name: typeof p.name === "string" ? p.name : "",
		location: typeof p.in === "string" ? p.in : "",
		required: p.required === true,
		schemaType: typeof schema.type === "string" ? schema.type : "string",
		description: typeof p.description === "string" ? p.description : "",
	};
}

/** Merge path-item and operation parameters (operation overrides path-item). */
function mergeParameters(doc: JsonNode, pathParams: JsonNode[], opParams: JsonNode[]): Parameter[] {
	const byKey = new Map<string, JsonNode>();
	for (const p of pathParams) {
		const resolved = resolveParameter(doc, p);
		if (resolved) byKey.set(paramKey(resolved), resolved);
	}
	for (const p of opParams) {
		const resolved = resolveParameter(doc, p);
		if (resolved) byKey.set(paramKey(resolved), resolved);
	}
	return [...byKey.values()].map((p) => flattenParameter(p));
}

/** Operation-level metadata for an endpoint. */
function getEndpointMeta(doc: JsonNode, endpoint: string): EndpointMeta | undefined {
	const parts = endpoint.split(" ");
	if (parts.length < 2) return undefined;
	const method = parts[0]!.toLowerCase();
	const path = parts.slice(1).join(" ");

	const paths = (doc.paths ?? {}) as Record<string, JsonNode>;
	const pathItem = paths[path];
	if (!pathItem || typeof pathItem !== "object") return undefined;

	const op = (pathItem as JsonNode)[method];
	if (!op || typeof op !== "object") return undefined;
	const opNode = op as JsonNode;

	const pathParams = Array.isArray(pathItem.parameters)
		? (pathItem.parameters as JsonNode[])
		: [];
	const opParams = Array.isArray(opNode.parameters) ? (opNode.parameters as JsonNode[]) : [];

	return {
		method: method.toUpperCase(),
		path,
		operationId: typeof opNode.operationId === "string" ? opNode.operationId : "",
		summary: typeof opNode.summary === "string" ? opNode.summary : "",
		description: typeof opNode.description === "string" ? opNode.description : "",
		tags: Array.isArray(opNode.tags) ? (opNode.tags as string[]) : [],
		parameters: mergeParameters(doc, pathParams, opParams),
	};
}

/**
 * Build the MCP discovery index: per-endpoint operation metadata plus the
 * top-level field names and named-schema refs that let an LLM discover and
 * navigate endpoints without pulling full schemas. Output is stable (sorted
 * by operation).
 */
function buildMcpIndex(doc: JsonNode): void {
	const endpoints = buildEndpointMap(doc);
	const operations = listEndpoints(doc);
	const endpointList = operations.map((operation) => {
		const meta = getEndpointMeta(doc, operation) ?? {
			method: "",
			path: "",
			operationId: "",
			summary: "",
			description: "",
			tags: [],
			parameters: [],
		};
		return {
			operation,
			method: meta.method,
			path: meta.path,
			operationId: meta.operationId,
			summary: meta.summary,
			description: meta.description,
			tags: meta.tags,
			parameters: meta.parameters,
			requestFields: getFieldNames(doc, endpoints, operation, "request"),
			requestSchemaRef: getSchemaRef(endpoints, operation, "request"),
			responseFields: getFieldNames(doc, endpoints, operation, "response"),
			responseSchemaRef: getSchemaRef(endpoints, operation, "response"),
		};
	});

	const mcpIndex = {
		version: 1,
		builtAt: new Date().toISOString(),
		source: "packages/sdk/apiV2.yaml",
		endpointCount: endpointList.length,
		endpoints: endpointList,
	};

	writeFileSync(MCP_PATH, `${JSON.stringify(mcpIndex, null, 2)}\n`, "utf8");
	console.error(`[beds24] wrote ${MCP_PATH} (${endpointList.length} endpoints).`);
}

main().catch((e) => {
	console.error(`[beds24] fatal: ${(e as Error).message}`);
	process.exit(1);
});
