/**
 * Generate TypeScript type declarations + the MCP discovery index from the
 * local apiV2.yaml.
 *
 *   bun run scripts/generate-types.ts
 *
 * Emits:
 *   src/sdk/generated/types.d.ts      — full type declarations (openapi-typescript)
 *   src/sdk/generated/mcp-index.json  — per-endpoint operation metadata, field
 *                                        names, and named-schema refs for the
 *                                        MCP `beds24_discover` tool.
 *
 * Both are auto-generated — do not edit either by hand.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import openapiTS, { astToString, type OpenAPI3 } from "openapi-typescript";
import yaml from "js-yaml";
import {
	getEndpointMeta,
	getFieldNames,
	getSchemaRef,
	listEndpoints,
} from "../src/sdk/schema.ts";

const SPEC_PATH = join(process.cwd(), "knowledge", "apiV2.yaml");
const OUT_DIR = join(process.cwd(), "src", "sdk", "generated");
const DTS_PATH = join(OUT_DIR, "types.d.ts");
const MCP_PATH = join(OUT_DIR, "mcp-index.json");

/** Facts dir the SchemaIndex resolves apiV2.yaml from — same as SPEC_PATH's dir. */
const FACTS_DIR = join(process.cwd(), "knowledge");

const BANNER = `// AUTO-GENERATED by scripts/generate-types.ts — do not edit.\n// Source: knowledge/apiV2.yaml (mirror of https://beds24.com/api/v2/apiV2.yaml)\n// Regenerate with: bun run generate-types.ts\n`;

async function main(): Promise<void> {
	// openapi-typescript's redoc-based parser rejects a bare file-path string
	// ("Unsupported schema format, expected `openapi: 3.x`"), so we parse the
	// YAML ourselves and hand it the resolved JSON object.
	let doc: OpenAPI3;
	try {
		doc = yaml.load(readFileSync(SPEC_PATH, "utf8")) as OpenAPI3;
	} catch (e) {
		console.error(`[beds24] failed to parse ${SPEC_PATH}: ${(e as Error).message}`);
		process.exit(1);
	}

	let ast;
	try {
		ast = await openapiTS(doc);
	} catch (e) {
		console.error(`[beds24] openapi-typescript failed to generate types: ${(e as Error).message}`);
		process.exit(1);
	}

	const dts = BANNER + "\n" + astToString(ast);

	mkdirSync(OUT_DIR, { recursive: true });
	writeFileSync(DTS_PATH, dts, "utf8");
	console.error(`[beds24] wrote ${DTS_PATH} (${dts.length} bytes).`);

	buildMcpIndex(FACTS_DIR);
}

/**
 * Build the MCP discovery index: per-endpoint operation metadata plus the
 * top-level field names and named-schema refs that let an LLM discover and
 * navigate endpoints without pulling full schemas. Reuses SchemaIndex to build
 * from the one spec parse. Output is stable (sorted by operation).
 */
function buildMcpIndex(factsDir: string): void {
	const operations = listEndpoints(factsDir); // already sorted
	const endpoints = operations.map((operation) => {
		const meta = getEndpointMeta(factsDir, operation) ?? {
			method: "",
			path: "",
			operationId: "",
			summary: "",
			description: "",
			tags: [],
			parameters: [],
		};
		return {
			operation,
			method: meta.method,
			path: meta.path,
			operationId: meta.operationId,
			summary: meta.summary,
			description: meta.description,
			tags: meta.tags,
			parameters: meta.parameters,
			requestFields: getFieldNames(factsDir, operation, "request"),
			requestSchemaRef: getSchemaRef(factsDir, operation, "request"),
			responseFields: getFieldNames(factsDir, operation, "response"),
			responseSchemaRef: getSchemaRef(factsDir, operation, "response"),
		};
	});

	const mcpIndex = {
		version: 1,
		builtAt: new Date().toISOString(),
		source: "knowledge/apiV2.yaml",
		endpointCount: endpoints.length,
		endpoints,
	};

	writeFileSync(MCP_PATH, JSON.stringify(mcpIndex, null, 2) + "\n", "utf8");
	console.error(`[beds24] wrote ${MCP_PATH} (${endpoints.length} endpoints).`);
}

main().catch((e) => {
	console.error(`[beds24] fatal: ${(e as Error).message}`);
	process.exit(1);
});
